## **Q1. Load the given retail sales dataset into a Pandas DataFrame and display the first 5 rows along with the dataset information to understand its structure.**

In [53]:
import pandas as pd
import numpy as np

In [63]:
#Ans1

# Loading retail data

df = pd.read_csv("/retail_dataset .csv")
df

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West
...,...,...,...,...,...,...,...
95,T096,C036,Furniture,10.0,2901.0,08-08-2023,North
96,T097,C021,Clothing,9.0,1077.0,19-07-2024,North
97,T098,C015,Clothing,7.0,643.0,13-08-2023,North
98,T099,C005,Groceries,9.0,429.0,20-01-2024,South
99,T100,C010,Furniture,8.0,1183.0,07-02-2024,North

In [39]:
# First 5 rows

df.head()

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West

In [40]:
# Dataset information to understand its structure.

df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    100 non-null    object
 1   Customer ID       100 non-null    object
 2   Product Category  97 non-null     object
 3   Quantity          98 non-null     float64
 4   Price             95 non-null     float64
 5   Date              100 non-null    object
 6   Region            98 non-null     object
dtypes: float64(2), object(5)
memory usage: 5.6+ KB

(100, 7)

## **Q2. Inspect the dataset and identify missing values in each column. Display the total number of missing values present in the dataset.**

In [41]:
# Ans2
# Identify missing values in each column

missing_values = df.isnull().sum()
missing_values

Transaction ID      0
Customer ID         0
Product Category    3
Quantity            2
Price               5
Date                0
Region              2
dtype: int64

In [42]:
# The total number of missing values present in the dataset.

total_missing_values = missing_values.sum()
total_missing_values

np.int64(12)

## **Q3. Replace missing values in the Quantity and Price columns with their respective mean values using Pandas.**

In [44]:
# Ans3
# Replacing missing values in the Quantity and Price columns

df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mean())
df['Price'] = df['Price'].fillna(df['Price'].mean())

In [47]:
# Checking whether missing values are still present or not.

print(df[['Quantity', 'Price']].isnull().sum())

Quantity    0
Price       0
dtype: int64

## **Q4. Remove all rows where the Product Category or Region column contains missing values.**

In [50]:
#Ans3
# Removing all rows where the Product Category or Region column contains missing values

df = df.dropna(subset=['Product Category', 'Region'])

In [51]:
# Checking whether those columns are removed or not.

df.shape

(95, 7)

## **Q5. Create a new column called Revenue using NumPy, where:**
- Revenue = Quantity × Price
- Display the updated dataset with the new column.

In [81]:
# Ans5
# Creating a new column called Revenue

df['Revenue'] = np.multiply(df['Quantity'], df['Price'])

# Displaying the updated dataset with the new column.

df.head()

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue,Month
0,T001,C015,Books,7.0,167.0,2023-02-02,North,1169.0,February
1,T002,C004,Toys,4.0,374.0,2023-02-17,South,1496.0,February
2,T003,C033,Furniture,8.0,1059.0,2024-05-17,South,8472.0,May
3,T004,C047,Groceries,5.0,304.0,2024-02-11,South,1520.0,February
4,T005,C022,Books,7.0,282.0,2024-07-27,West,1974.0,July

## **Q6. Using NumPy, calculate the total revenue generated from all transactions in the dataset.**

In [66]:
# Ans6

# Calculating the total revenue generated from all transactions in the dataset.

total_revenue = np.sum(df['Revenue'])
total_revenue

np.float64(462851.0)

## **Q7. Group the dataset by Product Category and calculate the total revenue generated by each category.**

In [67]:
# Ans7

# The total revenue generated by each category.

category_revenue = df.groupby('Product Category')['Revenue'].sum()
category_revenue

Product Category
Beauty          28691.0
Books           26523.0
Clothing        85006.0
Electronics     83358.0
Furniture      128844.0
Groceries       11978.0
Sports          34484.0
Toys            45270.0
Name: Revenue, dtype: float64

## **Q8. Based on the revenue calculated for each product category, identify the top 3 categories with the highest revenue and the bottom 3 categories with the lowest revenue.**

In [69]:
# Ans8

# Top 3 categories with the highest revenue.

top_3_categories = category_revenue.nlargest(3)
top_3_categories

Product Category
Furniture      128844.0
Clothing        85006.0
Electronics     83358.0
Name: Revenue, dtype: float64

In [70]:
# Bottom 3 categories with the lowest revenue.

bottom_3_categories = category_revenue.nsmallest(3)
bottom_3_categories

Product Category
Groceries    11978.0
Books        26523.0
Beauty       28691.0
Name: Revenue, dtype: float64

## **Q9. Group the dataset by Region and calculate the total revenue generated in each region. Identify the region with the highest revenue and the region with the lowest revenue.**

In [71]:
# Ans9

# Grouping the dataset by Region and calculate the total revenue generated in each region.

region_revenue = df.groupby('Region')['Revenue'].sum()
region_revenue

Region
East     128827.0
North    155132.0
South     97471.0
West      80377.0
Name: Revenue, dtype: float64

In [72]:
## Identify the region with the highest revenue and the region with the lowest revenue.

highest_revenue_region = region_revenue.idxmax()
lowest_revenue_region = region_revenue.idxmin()

print("Region with the highest revenue:", highest_revenue_region)
print("Region with the lowest revenue:", lowest_revenue_region)

Region with the highest revenue: North
Region with the lowest revenue: West

## **Q10. Extract the month from the Date column using Pandas and group the dataset by month to calculate thetotal monthly revenue. Also, calculate the mean, median, and standard deviation of the Revenue column using NumPy.**

In [76]:
#Ans10

# First convert Date column into Date time.

df['Date'] = pd.to_datetime(df['Date'], dayfirst = True)

# Extracting the month from the Date column using Pandas.

df['Month'] = df['Date'].dt.month_name()

# Grouping the dataset by month to calculate the total monthly revenue.

monthly_revenue = df.groupby('Month')['Revenue'].sum()
monthly_revenue

Month
April        56478.0
August       76958.0
December     44383.0
February     33028.0
January      43994.0
July         36919.0
June         37935.0
March        10557.0
May          27915.0
November     25150.0
October      42097.0
September    27437.0
Name: Revenue, dtype: float64

In [80]:
# Calculating the mean, median, and standard deviation of the Revenue column using NumPy.

mean_revenue = np.mean(df['Revenue'])
median_revenue = np.median(df['Revenue'])
std_revenue = np.std(df['Revenue'])

print("Mean Revenue:", mean_revenue)
print("Median Revenue:", median_revenue)
print("Standard Deviation of Revenue:", std_revenue)

Mean Revenue: 4976.89247311828
Median Revenue: nan
Standard Deviation of Revenue: 4764.814614548884